import { createSlice } from "@reduxjs/toolkit";


const initialState = {
  user: null, //user object (from database)
};

export const authSlice = createSlice({
  name: "auth",
  initialState,
  // methods to change the state
  // toolkit automatically creates action creators
  reducers: {

  },
});

export const {

} = authSlice.actions; //access the actions generated by redux tool kit (based on reducers)

export default authSlice.reducer;
