const mongoose = require("mongoose");
const User = require("../server/models/User"); // Your modified User model

// MongoDB connection URI
const mongoURI = process.env.MONGO_URL;

let cachedDb = null;

// Helper function to connect to MongoDB
async function connectToDatabase() {
  if (cachedDb) {
    return cachedDb;
  }

  const connection = await mongoose.connect(mongoURI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  cachedDb = connection;
  return cachedDb;
}

exports.handler = async (event) => {
  try {
    await connectToDatabase();

    // sub is unique id generated by cognito
    const { sub, email } = event.request.userAttributes;
    const newUser = new User({
      _id: sub,
      firstName: "",
      lastName: "",
      email,
      picturePath: "",
      friends: [],
    });

    const savedUser = await newUser.save();

    return {
      statusCode: 200,
      body: JSON.stringify({
        message: "User saved successfully",
        userId: savedUser._id,
      }),
    };
  } catch (error) {
    console.error("Error saving user:", error);
    return {
      statusCode: 500,
      body: JSON.stringify({ message: "Error saving user" }),
    };
  }
};
